--[[

Main details:

Universe id: 2583975875
Place id: 6805461391
Name: Generic Obby
Version: 9

Other information:

Last updated: 2021-05-25T00:04:49.000Z

This was determined from the Roblox Studio version history menu, which contains the date of the version in a human readable format, which was manually converted into the ISO 8601 format via an online website.

Deviation:

Scripts that load the content deleted virus were not commented out nor disabled.

]]

return nil