--[[

Main details:

Universe id: 3250484404
Place id: 8515170099
Version: 14
Name: Chart Obby

Roblox API stuff:

Description: A chart obby made by me.
Allowed gear genres: all
Allowed gear categories: none
Is genre enforced: true
Copying allowed: false
Visits: 0
Max players: 50
Created: 2022-01-11T19:20:40.433Z
Last updated: 2022-08-01T22:02:08.287Z
Studio access to APIs: false
Create private servers: false
Universe avatar type: morph to R15
Genre: all
genre_l1: ""
genre_l2: ""
Is all genre: true
Is favourited by user: false
Favourited count: 0

Deviation:

ReplicatedFirst script was not commented out.

]]